In [1]:
import seaborn as sns
import metapack as mp
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display 

%matplotlib inline
sns.set_context('notebook')
mp.jupyter.init()

from metapack_build.core import alt_col_name
import re

In [2]:

pkg = mp.jupyter.open_source_package()
pkg

# HUD Point in Time Counts by CoC
`hudexchange.com-pit-coc-1` Last Update: 2019-07-07T17:39:50

__


## Documentation Links

* [PIT and HIC Data Since 2007](https://www.hudexchange.info/resource/3031/pit-and-hic-data-since-2007/)



## Contacts

* **Wrangler** [Eric Busboom](mailto:eric@civicknowledge.com), [Civic Knowledge](http://civicknowledge.com)

## Resources

* ** [pitc_coc](notebooks/Combine.ipynb#df)**. Combined pitc, 2007 to 2018

## References

* **[pitc_coc_2018](https://www.hudexchange.info/resources/documents/2007-2018-PIT-Counts-by-CoC.xlsx#2018)**. 2007 - 2018 PIT Counts by CoC; 2018 workbook
* **[pitc_coc_2017](https://www.hudexchange.info/resources/documents/2007-2018-PIT-Counts-by-CoC.xlsx#2017)**. 2006 - 2018 PIT Counts by CoC; 2017 workbook
* **[pitc_coc_2016](https://www.hudexchange.info/resources/documents/2007-2018-PIT-Counts-by-CoC.xlsx#2016)**. 2005 - 2018 PIT Counts by CoC; 2016 workbook
* **[pitc_coc_2015](https://www.hudexchange.info/resources/documents/2007-2018-PIT-Counts-by-CoC.xlsx#2015)**. 2004 - 2018 PIT Counts by CoC; 2015 workbook
* **[pitc_coc_2014](https://www.hudexchange.info/resources/documents/2007-2018-PIT-Counts-by-CoC.xlsx#2014)**. 2003 - 2018 PIT Counts by CoC; 2014 workbook
* **[pitc_coc_2013](https://www.hudexchange.info/resources/documents/2007-2018-PIT-Counts-by-CoC.xlsx#2013)**. 2002 - 2018 PIT Counts by CoC; 2013 workbook
* **[pitc_coc_2012](https://www.hudexchange.info/resources/documents/2007-2018-PIT-Counts-by-CoC.xlsx#2012)**. 2001 - 2018 PIT Counts by CoC; 2012 workbook
* **[pitc_coc_2011](https://www.hudexchange.info/resources/documents/2007-2018-PIT-Counts-by-CoC.xlsx#2011)**. 2000 - 2018 PIT Counts by CoC; 2011 workbook
* **[pitc_coc_2010](https://www.hudexchange.info/resources/documents/2007-2018-PIT-Counts-by-CoC.xlsx#2010)**. 1999 - 2018 PIT Counts by CoC; 2010 workbook
* **[pitc_coc_2009](https://www.hudexchange.info/resources/documents/2007-2018-PIT-Counts-by-CoC.xlsx#2009)**. 1998 - 2018 PIT Counts by CoC; 2009 workbook
* **[pitc_coc_2008](https://www.hudexchange.info/resources/documents/2007-2018-PIT-Counts-by-CoC.xlsx#2008)**. 1997 - 2018 PIT Counts by CoC; 2008 workbook
* **[pitc_coc_2007](https://www.hudexchange.info/resources/documents/2007-2018-PIT-Counts-by-CoC.xlsx#2007)**. 1996 - 2018 PIT Counts by CoC; 2007 workbook

In [3]:
frames = []
for r in pkg.references():
    f = r.dataframe()
    if not 'year' in f.columns:
        f.insert(0,'year', value=int(r.Year))
    frames.append(f)

In [4]:
def munge_cols(df):
    return [re.sub(r'_\d\d\d\d', '', alt_col_name(c,i)) for i, c in enumerate(df.columns) ]

cols = []

# Check that the latest file has all of the columns that are in all of the earlier files
for f in frames:
    
    if not cols:
        cols = munge_cols(f)
    else:
        c1 = set(cols)
        c2 = set(munge_cols(f))
        assert not (c2-c1)
    
for f in reversed(frames):
    f.columns = munge_cols(f)

In [5]:
df = pd.concat(frames, sort=True)

In [10]:
str_cols = ['coc_number', 'coc_name', 'coc_category']
num_cols = [c for c in df.columns if c not in str_cols+['year']]
new_cols = ['year'] + str_cols + num_cols

In [13]:
# Get rid of the blanks and '.' that prevent most of the columns from being numbers 
strings = set()
for c in num_cols:
    s = df[c]
    strings |=set(s[s.apply(lambda x: isinstance(x, str))])
    
    df[c] = pd.to_numeric(df[c],errors='coerce')
 
df = df[new_cols].sort_values(['year','coc_number'])

In [14]:
df.head().T

,397,396,0,1,2
year,2007,2007,2007,2007,2007
coc_number,,,AK-500,AK-501,AL-500
coc_name,,Total,Anchorage CoC,Alaska Balance of State CoC,"Birmingham/Jefferson, St. Clair, Shelby Counti..."
coc_category,NaN,NaN,NaN,NaN,NaN
chronically_homeless,NaN,NaN,NaN,NaN,NaN
chronically_homeless_individuals,NaN,119813,224,54,516
chronically_homeless_people_in_families,NaN,NaN,NaN,NaN,NaN
homeless_children_of_parenting_youth,NaN,NaN,NaN,NaN,NaN
homeless_family_households,NaN,78535,93,97,228
homeless_individuals,NaN,412700,696,366,1529
homeless_parenting_youth_age_18_24,NaN,NaN,NaN,NaN,NaN
homeless_parenting_youth_under_18,NaN,NaN,NaN,NaN,NaN
homeless_parenting_youth_under_25,NaN,NaN,NaN,NaN,NaN
homeless_people_in_families,NaN,234558,278,302,575
homeless_unaccompanied_youth_age_18_24,NaN,NaN,NaN,NaN,NaN
homeless_unaccompanied_youth_under_18,NaN,NaN,NaN,NaN,NaN
homeless_unaccompanied_youth_under_25,NaN,NaN,NaN,NaN,NaN
homeless_veterans,NaN,NaN,NaN,NaN,NaN
overall_homeless,NaN,647258,974,668,2104
sheltered_es_chronically_homeless,NaN,NaN,NaN,NaN,NaN
sheltered_es_chronically_homeless_individuals,NaN,NaN,NaN,NaN,NaN
sheltered_es_chronically_homeless_people_in_families,NaN,NaN,NaN,NaN,NaN
sheltered_es_homeless,NaN,216659,548,350,465
sheltered_es_homeless_children_of_parenting_youth,NaN,NaN,NaN,NaN,NaN
sheltered_es_homeless_family_households,NaN,29586,39,56,31
sheltered_es_homeless_individuals,NaN,128169,438,180,393
sheltered_es_homeless_parenting_youth_age_18_24,NaN,NaN,NaN,NaN,NaN
sheltered_es_homeless_parenting_youth_under_18,NaN,NaN,NaN,NaN,NaN
sheltered_es_homeless_parenting_youth_under_25,NaN,NaN,NaN,NaN,NaN
sheltered_es_homeless_people_in_families,NaN,88490,110,170,72
...,...,...,...,...,...
sheltered_total_chronically_homeless,NaN,NaN,NaN,NaN,NaN
sheltered_total_chronically_homeless_individuals,NaN,41768,187,34,269
sheltered_total_chronically_homeless_people_in_families,NaN,NaN,NaN,NaN,NaN
sheltered_total_homeless,NaN,391401,842,545,1240
sheltered_total_homeless_children_of_parenting_youth,NaN,NaN,NaN,NaN,NaN
sheltered_total_homeless_family_households,NaN,60814,85,80,153
sheltered_total_homeless_individuals,NaN,213073,589,302,833
sheltered_total_homeless_parenting_youth_age_18_24,NaN,NaN,NaN,NaN,NaN
sheltered_total_homeless_parenting_youth_under_18,NaN,NaN,NaN,NaN,NaN
sheltered_total_homeless_parenting_youth_under_25,NaN,NaN,NaN,NaN,NaN
sheltered_total_homeless_people_in_families,NaN,178328,253,243,407
sheltered_total_homeless_unaccompanied_youth_age_18_24,NaN,NaN,NaN,NaN,NaN
sheltered_total_homeless_unaccompanied_youth_under_18,NaN,NaN,NaN,NaN,NaN
sheltered_total_homeless_unaccompanied_youth_under_25,NaN,NaN,NaN,NaN,NaN
sheltered_total_homeless_veterans,NaN,NaN,NaN,NaN,NaN
unsheltered_chronically_homeless,NaN,NaN,NaN,NaN,NaN
unsheltered_chronically_homeless_individuals,NaN,78045,37,20,247
unsheltered_chronically_homeless_people_in_families,NaN,NaN,NaN,NaN,NaN
unsheltered_homeless,NaN,255857,132,123,864
unsheltered_homeless_children_of_parenting_youth,NaN,NaN,NaN,NaN,NaN
unsheltered_homeless_family_households,NaN,17721,8,17,75
unsheltered_homeless_individuals,NaN,199627,107,64,696
unsheltered_homeless_parenting_youth_age_18_24,NaN,NaN,NaN,NaN,NaN
unsheltered_homeless_parenting_youth_under_18,NaN,NaN,NaN,NaN,NaN
unsheltered_homeless_parenting_youth_under_25,NaN,NaN,NaN,NaN,NaN
unsheltered_homeless_people_in_families,NaN,56230,25,59,168
unsheltered_homeless_unaccompanied_youth_age_18_24,NaN,NaN,NaN,NaN,NaN
unsheltered_homeless_unaccompanied_youth_under_18,NaN,NaN,NaN,NaN,NaN
unsheltered_homeless_unaccompanied_youth_under_25,NaN,NaN,NaN,NaN,NaN
unsheltered_homeless_veterans,NaN,NaN,NaN,NaN,NaN